// Standardised Search Service error codes and error type.
//
// Controllers and services throw `SearchError` so that every search failure is
// reported to clients with a stable machine-readable `code`, independent of the
// underlying provider. The platform error handler serialises `err.code`.
import { HttpError } from "../../validation.js";

export const SEARCH_ERROR_CODES = Object.freeze({
  INVALID_QUERY: "SEARCH_INVALID_QUERY",
  INVALID_FIELD: "SEARCH_INVALID_FIELD",
  INVALID_OPERATOR: "SEARCH_INVALID_OPERATOR",
  UNSUPPORTED_OPERATOR: "SEARCH_UNSUPPORTED_OPERATOR",
  OBJECT_TYPE_NOT_FOUND: "SEARCH_OBJECT_TYPE_NOT_FOUND",
  FIELD_NOT_SEARCHABLE: "SEARCH_FIELD_NOT_SEARCHABLE",
  FIELD_NOT_FILTERABLE: "SEARCH_FIELD_NOT_FILTERABLE",
  FIELD_NOT_SORTABLE: "SEARCH_FIELD_NOT_SORTABLE",
  FIELD_NOT_FACETABLE: "SEARCH_FIELD_NOT_FACETABLE",
  QUERY_TOO_COMPLEX: "SEARCH_QUERY_TOO_COMPLEX",
  WILDCARD_TOO_BROAD: "SEARCH_WILDCARD_TOO_BROAD",
  TIMEOUT: "SEARCH_TIMEOUT",
  PROVIDER_UNAVAILABLE: "SEARCH_PROVIDER_UNAVAILABLE",
  INDEX_NOT_FOUND: "SEARCH_INDEX_NOT_FOUND",
  INDEXING_FAILED: "SEARCH_INDEXING_FAILED",
  REBUILD_IN_PROGRESS: "SEARCH_REBUILD_IN_PROGRESS",
  SAVED_SEARCH_NOT_FOUND: "SEARCH_SAVED_SEARCH_NOT_FOUND",
  SAVED_SEARCH_ACCESS_DENIED: "SEARCH_SAVED_SEARCH_ACCESS_DENIED",
  UNAUTHORIZED: "SEARCH_UNAUTHORIZED",
  TENANT_ACCESS_DENIED: "SEARCH_TENANT_ACCESS_DENIED",
});

const DEFAULT_STATUS = {
  [SEARCH_ERROR_CODES.INVALID_QUERY]: 400,
  [SEARCH_ERROR_CODES.INVALID_FIELD]: 400,
  [SEARCH_ERROR_CODES.INVALID_OPERATOR]: 400,
  [SEARCH_ERROR_CODES.UNSUPPORTED_OPERATOR]: 400,
  [SEARCH_ERROR_CODES.OBJECT_TYPE_NOT_FOUND]: 404,
  [SEARCH_ERROR_CODES.FIELD_NOT_SEARCHABLE]: 400,
  [SEARCH_ERROR_CODES.FIELD_NOT_FILTERABLE]: 400,
  [SEARCH_ERROR_CODES.FIELD_NOT_SORTABLE]: 400,
  [SEARCH_ERROR_CODES.FIELD_NOT_FACETABLE]: 400,
  [SEARCH_ERROR_CODES.QUERY_TOO_COMPLEX]: 400,
  [SEARCH_ERROR_CODES.WILDCARD_TOO_BROAD]: 400,
  [SEARCH_ERROR_CODES.TIMEOUT]: 504,
  [SEARCH_ERROR_CODES.PROVIDER_UNAVAILABLE]: 503,
  [SEARCH_ERROR_CODES.INDEX_NOT_FOUND]: 404,
  [SEARCH_ERROR_CODES.INDEXING_FAILED]: 500,
  [SEARCH_ERROR_CODES.REBUILD_IN_PROGRESS]: 409,
  [SEARCH_ERROR_CODES.SAVED_SEARCH_NOT_FOUND]: 404,
  [SEARCH_ERROR_CODES.SAVED_SEARCH_ACCESS_DENIED]: 403,
  [SEARCH_ERROR_CODES.UNAUTHORIZED]: 403,
  [SEARCH_ERROR_CODES.TENANT_ACCESS_DENIED]: 403,
};

export class SearchError extends HttpError {
  constructor(code, message, options = {}) {
    const status = options.status ?? DEFAULT_STATUS[code] ?? 400;
    super(status, message, options.details ?? null);
    this.code = code;
  }
}

export function searchError(code, message, options) {
  return new SearchError(code, message, options);
}
