export { checkPermission, checkPermissionAudited, effectivePermissions } from "./services/authorization.js";
export { effectiveAccess } from "./services/access.js";
export {
  ancestorOrganizationIds,
  descendantOrganizationIds,
  organizationContext,
  getOrganization,
  listUserOrganizations,
  tenantIdOf,
} from "./services/orgs.js";
export { getHierarchy, getSettings, getSetting } from "./services/hierarchy.js";
export { login as authenticateWithPassword, completeMfa, startSso, completeSso } from "./services/authentication.js";
export { createSession, getSessionByToken as requireActiveSession } from "./services/sessions.js";
export { resolveConfig, resolveAll as resolveAllConfig } from "./services/config.js";
export {
  getTenant,
  tenantContext,
  homeTenantId,
  tenantIdOfOrganization,
  resolveTenant,
  assertTenantScope,
} from "./services/tenants.js";
export {
  resolveType,
  effectiveAttributes,
  attributeContract,
  validateRecord,
  assertValidRecord,
  renderForm,
  renderType,
  resolveLov,
  assertValueInLov,
  evaluate as evaluateRule,
  resolveArtifactConfig,
  assertEnabled as assertMetadataEnabled,
} from "./services/metadata.js";

// Object & Relationship Framework
export {
  createObject,
  getObject,
  listObjects,
  updateObject,
  setObjectStatus,
  softDeleteObject,
  restoreObject,
  objectTypes,
  objectSummary,
  listObjectVersions,
  getObjectVersion,
  objectLocks,
  checkoutObject,
  checkinObject,
  bulkCreateObjects,
  bulkMutateObjects,
  listRelationshipTypes,
  getRelationshipType,
  createRelationshipType,
  updateRelationshipType,
  setRelationshipTypeStatus,
  deleteRelationshipType,
  listRelationships,
  getRelationship,
  createRelationship,
  validateRelationship,
  updateRelationship,
  deleteRelationship,
  relationshipsForObject,
  traverse as traverseObjects,
  graph as objectGraph,
  listReferences,
  getReference,
  createReference,
  updateReference,
  deleteReference,
  orphanReferences,
  directDependencies,
  impactOf,
  detectCycles,
  safeDeleteReport,
} from "./services/objects.js";

// Lifecycle Management
export {
  listStatuses,
  getStatus,
  findStatus,
  createStatus,
  updateStatus,
  setStatusStatus,
  deleteStatus,
  listDefinitions,
  getDefinition,
  findDefinition,
  createDefinition,
  updateDefinition,
  setDefinitionStatus,
  deleteDefinition,
  listVersions,
  createVersion,
  validateDefinition,
  validateDefinitionVersion,
  publishDefinition,
  listStates,
  createState,
  updateState,
  deleteState,
  listTransitions,
  createTransition,
  updateTransition,
  deleteTransition,
  listAssignments,
  createAssignment,
  deleteAssignment,
  resolveAssignment,
  initialStateForVersion,
  transitionsFrom,
  applyInitialLifecycle,
  availableTransitions,
  objectLifecycle,
  transitionObject,
  statusHistory,
  requestObjectRelease,
  objectReleases,
  applyTransition,
  assignLifecycle,
  recordStatusHistory,
  listRules,
  getRule,
  createRule,
  updateRule,
  deleteRule,
  listReleaseRules,
  listApprovalRules,
  resolveRule,
  requestRelease,
  decideApproval,
  resubmit,
  listReleases,
  registerWorkflowExecutor,
  workflowExecutor,
  resolveApprovers,
} from "./services/lifecycle.js";

// Workflow & Process Engine
export {
  validateGraph as validateWorkflowGraph,
  autoLayout as autoLayoutWorkflow,
  startInstance as startWorkflowInstance,
  advance as advanceWorkflow,
  getInstance as getWorkflowInstance,
  listInstances as listWorkflowInstances,
  pauseInstance as pauseWorkflowInstance,
  resumeInstance as resumeWorkflowInstance,
  cancelInstance as cancelWorkflowInstance,
  retryInstance as retryWorkflowInstance,
  instanceHistory as workflowInstanceHistory,
  triggerEvent as triggerWorkflowEvent,
  completeTask as completeWorkflowTask,
  decideApproval as decideWorkflowApproval,
  sweepEscalations as sweepWorkflowEscalations,
  registerServiceHandler as registerWorkflowServiceHandler,
  resolveAssignee as resolveWorkflowAssignee,
} from "./services/workflow.js";

export {
  getDefinition as getWorkflowDefinition,
  findDefinition as findWorkflowDefinition,
  listDefinitions as listWorkflowDefinitions,
  createDefinition as createWorkflowDefinition,
  updateDefinition as updateWorkflowDefinition,
  setDefinitionStatus as setWorkflowDefinitionStatus,
  deleteDefinition as deleteWorkflowDefinition,
  listVersions as listWorkflowVersions,
  createVersion as createWorkflowVersion,
  validateDefinition as validateWorkflowDefinition,
  publishDefinition as publishWorkflowDefinition,
  cloneDefinition as cloneWorkflowDefinition,
  designerContext as workflowDesignerContext,
  listTasks as listWorkflowTasks,
  listApprovals as listWorkflowApprovals,
  listRoutingRules as listWorkflowRoutingRules,
  listEscalationRules as listWorkflowEscalationRules,
  listBindings as listWorkflowBindings,
  listNotifications as listWorkflowNotifications,
  listTemplates as listWorkflowNotificationTemplates,
} from "./services/workflow.js";

// Audit & History Framework — reusable platform capability. Business modules
// call `recordAuditEvent`/`recordObjectChange` for explicit events or attach
// `auditRoute` to express routes for automatic capture.
export {
  capture as recordAuditEvent,
  writeAudit,
  recordObjectChange,
  resolvePolicy as resolveAuditPolicy,
  listEvents as listAuditEvents,
  getEvent as getAuditEvent,
  objectHistory as auditObjectHistory,
  userActivity as auditUserActivity,
  auditSummary,
  eventFacets as auditEventFacets,
  listPolicies as listAuditPolicies,
  createPolicy as createAuditPolicy,
  updatePolicy as updateAuditPolicy,
  exportEvents as exportAuditEvents,
  runRetention as runAuditRetention,
  auditFromRequest,
  auditRoute,
} from "./services/audit.js";

// Notification & Communication Framework — reusable platform capability.
// Business modules publish domain events with `publishNotificationEvent` and the
// framework resolves rules, recipients, templates and preferences.
export {
  CHANNELS as notificationChannels,
  PRIORITIES as notificationPriorities,
  RECIPIENT_TYPES as notificationRecipientTypes,
  TEMPLATE_ROOTS as notificationTemplateRoots,
  publish as publishNotificationEvent,
  notifyUser,
  notifyGroup,
  notifyRole,
  deliverDirect as deliverNotificationDirect,
  listInbox,
  unreadCount as notificationUnreadCount,
  getNotification,
  markRead as markNotificationRead,
  markUnread as markNotificationUnread,
  markAllRead as markAllNotificationsRead,
  archiveNotification,
  deleteNotification,
  getPreferences as getNotificationPreferences,
  updatePreferences as updateNotificationPreferences,
  listTemplates as listNotificationTemplates,
  createTemplate as createNotificationTemplate,
  updateTemplate as updateNotificationTemplate,
  previewTemplate as previewNotificationTemplate,
  testSendTemplate as testSendNotificationTemplate,
  listRules as listNotificationRules,
  createRule as createNotificationRule,
  updateRule as updateNotificationRule,
  simulateRule as simulateNotificationRule,
  listProviders as listNotificationProviders,
  createProvider as createNotificationProvider,
  updateProvider as updateNotificationProvider,
  testProvider as testNotificationProvider,
  listEvents as listNotificationEvents,
  getEvent as getNotificationEvent,
  listHistory as listNotificationHistory,
  listDeliveries as listNotificationDeliveries,
  processQueue as processNotificationQueue,
  retryDelivery as retryNotificationDelivery,
  deliveryStats as notificationDeliveryStats,
  listReminders as listNotificationReminders,
  sweepReminders as sweepNotificationReminders,
  cancelRemindersForObject,
} from "./services/notifications.js";
