export { checkPermission, checkPermissionAudited, effectivePermissions } from "./services/authorization.js";
export { effectiveAccess } from "./services/access.js";
export {
  ancestorOrganizationIds,
  descendantOrganizationIds,
  organizationContext,
  getOrganization,
  listUserOrganizations,
  tenantIdOf,
} from "./services/orgs.js";
export { getHierarchy, getSettings, getSetting } from "./services/hierarchy.js";
export { login as authenticateWithPassword, completeMfa, startSso, completeSso } from "./services/authentication.js";
export { createSession, getSessionByToken as requireActiveSession } from "./services/sessions.js";
export { resolveConfig, resolveAll as resolveAllConfig } from "./services/config.js";
export {
  getTenant,
  tenantContext,
  homeTenantId,
  tenantIdOfOrganization,
  resolveTenant,
  assertTenantScope,
} from "./services/tenants.js";
export {
  resolveType,
  effectiveAttributes,
  attributeContract,
  validateRecord,
  assertValidRecord,
  renderForm,
  renderType,
  resolveLov,
  assertValueInLov,
  evaluate as evaluateRule,
  resolveArtifactConfig,
  assertEnabled as assertMetadataEnabled,
} from "./services/metadata.js";

// Object & Relationship Framework
export {
  createObject,
  getObject,
  listObjects,
  updateObject,
  setObjectStatus,
  softDeleteObject,
  restoreObject,
  objectTypes,
  objectSummary,
  listObjectVersions,
  getObjectVersion,
  objectLocks,
  checkoutObject,
  checkinObject,
  bulkCreateObjects,
  bulkMutateObjects,
  listRelationshipTypes,
  getRelationshipType,
  createRelationshipType,
  updateRelationshipType,
  setRelationshipTypeStatus,
  deleteRelationshipType,
  listRelationships,
  getRelationship,
  createRelationship,
  validateRelationship,
  updateRelationship,
  deleteRelationship,
  relationshipsForObject,
  traverse as traverseObjects,
  graph as objectGraph,
  listReferences,
  getReference,
  createReference,
  updateReference,
  deleteReference,
  orphanReferences,
  directDependencies,
  impactOf,
  detectCycles,
  safeDeleteReport,
} from "./services/objects.js";

// Lifecycle Management
export {
  listStatuses,
  getStatus,
  findStatus,
  createStatus,
  updateStatus,
  setStatusStatus,
  deleteStatus,
  listDefinitions,
  getDefinition,
  findDefinition,
  createDefinition,
  updateDefinition,
  setDefinitionStatus,
  deleteDefinition,
  listVersions,
  createVersion,
  validateDefinition,
  validateDefinitionVersion,
  publishDefinition,
  listStates,
  createState,
  updateState,
  deleteState,
  listTransitions,
  createTransition,
  updateTransition,
  deleteTransition,
  listAssignments,
  createAssignment,
  deleteAssignment,
  resolveAssignment,
  initialStateForVersion,
  transitionsFrom,
  applyInitialLifecycle,
  availableTransitions,
  objectLifecycle,
  transitionObject,
  statusHistory,
  requestObjectRelease,
  objectReleases,
  applyTransition,
  assignLifecycle,
  recordStatusHistory,
  listRules,
  getRule,
  createRule,
  updateRule,
  deleteRule,
  listReleaseRules,
  listApprovalRules,
  resolveRule,
  requestRelease,
  decideApproval,
  resubmit,
  listReleases,
  registerWorkflowExecutor,
  workflowExecutor,
  resolveApprovers,
} from "./services/lifecycle.js";

// Workflow & Process Engine
export {
  validateGraph as validateWorkflowGraph,
  autoLayout as autoLayoutWorkflow,
  startInstance as startWorkflowInstance,
  advance as advanceWorkflow,
  getInstance as getWorkflowInstance,
  listInstances as listWorkflowInstances,
  pauseInstance as pauseWorkflowInstance,
  resumeInstance as resumeWorkflowInstance,
  cancelInstance as cancelWorkflowInstance,
  retryInstance as retryWorkflowInstance,
  instanceHistory as workflowInstanceHistory,
  triggerEvent as triggerWorkflowEvent,
  completeTask as completeWorkflowTask,
  decideApproval as decideWorkflowApproval,
  sweepEscalations as sweepWorkflowEscalations,
  registerServiceHandler as registerWorkflowServiceHandler,
  resolveAssignee as resolveWorkflowAssignee,
} from "./services/workflow.js";

export {
  getDefinition as getWorkflowDefinition,
  findDefinition as findWorkflowDefinition,
  listDefinitions as listWorkflowDefinitions,
  createDefinition as createWorkflowDefinition,
  updateDefinition as updateWorkflowDefinition,
  setDefinitionStatus as setWorkflowDefinitionStatus,
  deleteDefinition as deleteWorkflowDefinition,
  listVersions as listWorkflowVersions,
  createVersion as createWorkflowVersion,
  validateDefinition as validateWorkflowDefinition,
  publishDefinition as publishWorkflowDefinition,
  cloneDefinition as cloneWorkflowDefinition,
  designerContext as workflowDesignerContext,
  listTasks as listWorkflowTasks,
  listApprovals as listWorkflowApprovals,
  listRoutingRules as listWorkflowRoutingRules,
  listEscalationRules as listWorkflowEscalationRules,
  listBindings as listWorkflowBindings,
  listNotifications as listWorkflowNotifications,
  listTemplates as listWorkflowNotificationTemplates,
} from "./services/workflow.js";

// Audit & History Framework — reusable platform capability. Business modules
// call `recordAuditEvent`/`recordObjectChange` for explicit events or attach
// `auditRoute` to express routes for automatic capture.
export {
  capture as recordAuditEvent,
  writeAudit,
  recordObjectChange,
  resolvePolicy as resolveAuditPolicy,
  listEvents as listAuditEvents,
  getEvent as getAuditEvent,
  objectHistory as auditObjectHistory,
  userActivity as auditUserActivity,
  auditSummary,
  eventFacets as auditEventFacets,
  listPolicies as listAuditPolicies,
  createPolicy as createAuditPolicy,
  updatePolicy as updateAuditPolicy,
  exportEvents as exportAuditEvents,
  runRetention as runAuditRetention,
  auditFromRequest,
  auditRoute,
} from "./services/audit.js";

// Notification & Communication Framework — reusable platform capability.
// Business modules publish domain events with `publishNotificationEvent` and the
// framework resolves rules, recipients, templates and preferences.
export {
  CHANNELS as notificationChannels,
  PRIORITIES as notificationPriorities,
  RECIPIENT_TYPES as notificationRecipientTypes,
  TEMPLATE_ROOTS as notificationTemplateRoots,
  publish as publishNotificationEvent,
  notifyUser,
  notifyGroup,
  notifyRole,
  deliverDirect as deliverNotificationDirect,
  listInbox,
  unreadCount as notificationUnreadCount,
  getNotification,
  markRead as markNotificationRead,
  markUnread as markNotificationUnread,
  markAllRead as markAllNotificationsRead,
  archiveNotification,
  deleteNotification,
  getPreferences as getNotificationPreferences,
  updatePreferences as updateNotificationPreferences,
  listTemplates as listNotificationTemplates,
  createTemplate as createNotificationTemplate,
  updateTemplate as updateNotificationTemplate,
  previewTemplate as previewNotificationTemplate,
  testSendTemplate as testSendNotificationTemplate,
  listRules as listNotificationRules,
  createRule as createNotificationRule,
  updateRule as updateNotificationRule,
  simulateRule as simulateNotificationRule,
  listProviders as listNotificationProviders,
  createProvider as createNotificationProvider,
  updateProvider as updateNotificationProvider,
  testProvider as testNotificationProvider,
  listEvents as listNotificationEvents,
  getEvent as getNotificationEvent,
  listHistory as listNotificationHistory,
  listDeliveries as listNotificationDeliveries,
  processQueue as processNotificationQueue,
  retryDelivery as retryNotificationDelivery,
  deliveryStats as notificationDeliveryStats,
  listReminders as listNotificationReminders,
  sweepReminders as sweepNotificationReminders,
  cancelRemindersForObject,
} from "./services/notifications.js";

// Communication & Delivery Services — reusable outbound delivery capability.
// Business modules (including the Notification Management module) submit
// rendered messages with `submitDeliveryRequest`; this module owns provider
// configuration, queue/worker processing, retry/dead-letter handling, reminders,
// escalations and delivery tracking.
export {
  DELIVERY_STATUSES,
  REMINDER_STATUSES,
  ESCALATION_STATUSES,
  submitRequest as submitDeliveryRequest,
  ingestNotification as ingestNotificationDelivery,
  getRequest as getDeliveryRequest,
  listRequests as listDeliveryRequests,
  cancelRequest as cancelDeliveryRequest,
  retryRequest as retryDeliveryRequest,
  listAttempts as listDeliveryAttempts,
  requestsForNotification as deliveryRequestsForNotification,
  processDue as processDeliveryQueue,
  pendingCount as pendingDeliveryCount,
  listDeliveryProviders,
  getDeliveryProvider,
  createDeliveryProvider,
  updateDeliveryProvider,
  deleteDeliveryProvider,
  setDeliveryProviderStatus,
  testDeliveryProvider,
  resolveProviderChain,
  recordProviderFailure,
  listProviderFailures,
  providerHealth as deliveryProviderHealth,
  scheduleReminder as scheduleDeliveryReminder,
  listReminders as listDeliveryReminders,
  getReminder as getDeliveryReminder,
  updateReminder as updateDeliveryReminder,
  cancelReminder as cancelDeliveryReminder,
  completeRemindersForObject as completeDeliveryRemindersForObject,
  sweepReminders as sweepDeliveryReminders,
  scheduleEscalation as scheduleDeliveryEscalation,
  listEscalations as listDeliveryEscalations,
  getEscalation as getDeliveryEscalation,
  cancelEscalation as cancelDeliveryEscalation,
  sweepEscalations as sweepDeliveryEscalations,
  completeEscalationsForObject as completeDeliveryEscalationsForObject,
  deliveryMetrics,
  deliveryStats as deliveryStatsSummary,
  deliveryTimeseries as deliveryTimeseriesData,
  providerFailureSummary as deliveryProviderFailureSummary,
  createAlert as createDeliveryAlert,
  listAlerts as listDeliveryAlerts,
  acknowledgeAlert as acknowledgeDeliveryAlert,
  registerTransport as registerDeliveryTransport,
  registerCustomTransport as registerCustomDeliveryTransport,
  rateLimitStatus as deliveryRateLimitStatus,
  assertDeliveryRateLimit,
} from "./services/delivery.js";

// Background Job Management — centralized asynchronous job registry,
// submission, monitoring, control, history, dependencies and results. Business
// modules submit jobs with `submitJob` and receive a Job ID immediately; the
// separate Job Scheduling & Execution Engine performs the work.
export {
  JOB_STATUSES,
  JOB_STATUS_LABELS,
  TERMINAL_STATUSES as TERMINAL_JOB_STATUSES,
  SUBMITTED_AS as JOB_SUBMITTED_AS,
  ARTIFACT_KINDS as JOB_ARTIFACT_KINDS,
  PRIORITIES as JOB_PRIORITIES,
  isTerminalStatus as isTerminalJobStatus,
  statusLabel as jobStatusLabel,
  submitJob,
  getJob,
  getStatus as getJobStatus,
  listJobs,
  transitionJob,
  updateProgress as updateJobProgress,
  cancelJob,
  retryJob,
  pauseJob,
  resumeJob,
  listDependencies as listJobDependencies,
  addDependencies as addJobDependencies,
  removeDependency as removeJobDependency,
  listChildren as listChildJobs,
  listHistory as listJobHistory,
  jobTimeline,
  resultPayload as jobResultPayload,
  setJobResult,
  addArtifact as addJobArtifact,
  listArtifacts as listJobArtifacts,
  listJobTypes,
  getJobType,
  createJobType,
  updateJobType,
  setJobTypeStatus,
  ensureDefaultJobTypes,
  jobMetrics,
  jobStatusCounts,
  jobTimeseries as jobTimeseriesData,
} from "./services/jobs.js";

// Job Scheduling & Execution Engine — queues, workers, schedules, retries,
// timeouts, cancellation, dead-letter, metrics and health. The engine owns
// execution only; business handlers are registered by the owning modules.
export {
  LOGICAL_QUEUES as JOB_LOGICAL_QUEUES,
  DEFAULT_QUEUES as JOB_DEFAULT_QUEUES,
  SCHEDULE_TYPES as JOB_SCHEDULE_TYPES,
  SCHEDULE_STATUSES as JOB_SCHEDULE_STATUSES,
  FAILURE_POLICIES as JOB_SCHEDULE_FAILURE_POLICIES,
  CONCURRENCY_POLICIES as JOB_SCHEDULE_CONCURRENCY_POLICIES,
  CATCHUP_POLICIES as JOB_SCHEDULE_CATCHUP_POLICIES,
  RETRY_STRATEGIES as JOB_RETRY_STRATEGIES,
  WORKER_STATUSES as JOB_WORKER_STATUSES,
  DEAD_LETTER_STATUSES as JOB_DEAD_LETTER_STATUSES,
  ERROR_CATEGORIES as JOB_ERROR_CATEGORIES,
  JobError,
  JobTimeoutError,
  JobCancelledError,
  categoryLabel as jobErrorCategoryLabel,
  isRetryableCategory as isRetryableJobError,
  classifyError as classifyJobError,
  canonicalQueue as canonicalJobQueue,
  ensureDefaultQueues,
  listQueues as listJobQueues,
  getQueue as getJobQueue,
  createQueue as createJobQueue,
  updateQueue as updateJobQueue,
  setQueueEnabled as setJobQueueEnabled,
  setQueuePaused as setJobQueuePaused,
  queueHealth as jobQueueHealth,
  listSchedules as listJobSchedules,
  getSchedule as getJobSchedule,
  createSchedule as createJobSchedule,
  updateSchedule as updateJobSchedule,
  setScheduleEnabled as setJobScheduleEnabled,
  setScheduleStatus as setJobScheduleStatus,
  runScheduleNow as runJobScheduleNow,
  listScheduleRuns as listJobScheduleRuns,
  sweepSchedules as sweepJobSchedules,
  computeNextRun as computeJobNextRun,
  describeSchedule as describeJobSchedule,
  listDeadLetters as listJobDeadLetters,
  requeueDeadLetter as retryJobDeadLetter,
  discardDeadLetter as discardJobDeadLetter,
  listWorkers as listJobWorkers,
  registerWorker as registerJobWorker,
  reapStaleWorkers as reapStaleJobWorkers,
  registerHandler as registerJobHandler,
  unregisterHandler as unregisterJobHandler,
  listHandlers as listJobHandlers,
  claimJob,
  runJobNow as runJobNowSync,
  processOnce as processJobsOnce,
  promoteReadyJobs,
  recoverStaleJobs,
  reapTimedOutJobs,
  requestCancellation as requestJobCancellation,
  effectiveMaxRetries as jobEffectiveMaxRetries,
  computeRetryDelay as computeJobRetryDelay,
  decideRetry as decideJobRetry,
  engineMaintenance as jobEngineMaintenance,
  executionMetrics as jobExecutionMetrics,
  createWorker as createJobWorker,
  EngineWorker as JobEngineWorker,
  acquireLock as acquireJobLock,
  releaseLock as releaseJobLock,
  getLock as getJobLock,
  registerDemoHandlers as registerDemoJobHandlers,
  recordEngineAudit as recordJobEngineAudit,
} from "./services/job-execution.js";

// Document & File Management module. The module facade is re-exported here so
// platform consumers can use files without importing service internals. The
// physical storage/processing capability lives in the File Storage & Processing
// Services module.
export {
  FILE_STATUSES,
  FILE_STATUS_LABELS,
  VERSION_STATUSES,
  UPLOAD_STATUSES,
  SECURITY_CLASSIFICATIONS,
  FILE_CATEGORIES,
  FILE_PERMISSIONS,
  FILE_EVENT_TYPES,
  vocabulary as FILE_VOCABULARY,
  validateUploadInput,
  sanitizeFilename,
  mimeFor,
  extensionOf,
  categoryForMime,
} from "./services/files.js";

export {
  canAccess as canAccessFile,
  assertAccess as assertFileAccess,
  effectivePermissions as fileEffectivePermissions,
  grantPermission as grantFilePermission,
  revokePermission as revokeFilePermission,
  listPermissions as listFilePermissions,
  RESOURCE_PERMISSION_MAP as FILE_RESOURCE_PERMISSION_MAP,
} from "./services/files.js";

export {
  listFiles,
  getFile,
  updateFileMetadata,
  deleteFile,
  restoreFile,
  moveFile,
  fileFacets,
  listFileEvents,
  listFolders,
  folderTree,
  getFolder,
  createFolder,
  updateFolder,
  deleteFolder,
  restoreFolder,
  listFolderFiles,
  moveFilesToFolder,
  removeFileFromFolder,
  folderBreadcrumb,
  listVersions as listFileVersions,
  getVersion as getFileVersion,
  createVersion as createFileVersion,
  restoreVersion as restoreFileVersion,
  versionDownload as fileVersionDownload,
  checkOutFile,
  checkInFile,
  getLock as getFileLock,
  listLocks as listFileLocks,
  releaseLock as releaseFileLock,
  forceReleaseLock,
  releaseExpiredLocks as releaseExpiredFileLocks,
  initiateUpload,
  uploadChunk,
  completeUpload,
  abortUpload,
  getUpload,
  listUploads,
  expireUploads,
  listFileAssociations,
  listObjectAssociations,
  createAssociation as createFileAssociation,
  updateAssociation as updateFileAssociation,
  removeAssociation as removeFileAssociation,
  listCollections,
  getCollection,
  createCollection,
  updateCollection,
  deleteCollection,
  addCollectionMembers,
  removeCollectionMember,
  listCollectionsForFile,
  getProcessingStatus as getFileProcessingStatus,
  requeueProcessing as requeueFileProcessing,
  registerFileProcessingHandlers,
  fileMetrics,
  storageBreakdown as fileStorageBreakdown,
  processingSummary as fileProcessingSummary,
} from "./services/files.js";

// Search & Discovery Framework. A shared platform capability: business modules
// register searchable object types and emit change hooks; consumers query
// through the provider-based search service.
export {
  SEARCH_SCOPES,
  SEARCH_STRATEGIES,
  SEARCH_SORTS,
  FILTER_OPERATORS,
  vocabulary as SEARCH_VOCABULARY,
  listObjectTypes as listSearchObjectTypes,
  getObjectType as getSearchObjectType,
  registerObjectType as registerSearchObjectType,
  updateObjectType as updateSearchObjectType,
  setObjectTypeStatus as setSearchObjectTypeStatus,
  deleteObjectType as deleteSearchObjectType,
  initializeSearch,
  searchableObjectTypes,
  searchableObjectTypeCodes,
  indexingStatus as searchIndexingStatus,
  listIndexFailures as listSearchIndexFailures,
  retryIndexFailures as retrySearchIndexFailures,
  drainIndexQueue,
  reindexObject as reindexSearchObject,
  reindexType as reindexSearchType,
  reindexTenant as reindexSearchTenant,
  pruneIndex as pruneSearchIndex,
  applyIndexChange,
  registerSourceResolver as registerSearchSourceResolver,
  listSourceResolvers as listSearchSourceResolvers,
  search,
  advancedSearch,
  fullTextSearch,
  searchByType,
  searchByAttributes,
  searchByRelationship,
  getFacets as getSearchFacets,
  getSuggestions as getSearchSuggestions,
  listSavedSearches,
  getSavedSearch,
  createSavedSearch,
  updateSavedSearch,
  deleteSavedSearch,
  runSavedSearch,
  listSearchHistory,
  clearSearchHistory,
  deleteSearchHistoryEntry,
  pruneSearchHistory,
  requestExport as requestSearchExport,
  runExport as runSearchExport,
  listExports as listSearchExports,
  getExport as getSearchExport,
  expireExports as expireSearchExports,
  getConfiguration as getSearchConfiguration,
  updateConfiguration as updateSearchConfiguration,
  registerSearchProvider,
  listSearchProviders,
  searchMetrics,
  searchHealth,
  emitObjectIndexChange,
  emitObjectChanged,
  emitFileChanged,
  registerSearchHandlers,
  runSearchMaintenance,
} from "./services/search.js";
