// Public facade for the Lifecycle Management module. Business modules should
// depend on this file (or the platform.js re-exports) rather than the internal
// services, so the layout can evolve without breaking consumers.

export {
  STATUS_CATEGORIES,
  LEGACY_OBJECT_STATUSES,
  DEFINITION_STATUSES,
  VERSION_STATUSES,
  TRANSITION_STATUSES,
  APPROVAL_RULE_KINDS,
  APPROVER_TYPES,
  APPROVAL_MODES,
  RELEASE_STATUSES,
  APPROVAL_STATUSES,
  APPROVAL_DECISIONS,
} from "./lifecycle/validation.js";

export {
  publicStatus,
  getStatusRow,
  findStatus,
  getStatus,
  listStatuses,
  createStatus,
  updateStatus,
  setStatusStatus,
  deleteStatus,
  defaultStatusRow,
  legacyForCategory,
  readStatusTenant,
  getStatusRowAsync,
  findStatusAsync,
  getStatusAsync,
  listStatusesAsync,
  createStatusAsync,
  updateStatusAsync,
  setStatusStatusAsync,
  deleteStatusAsync,
  defaultStatusRowAsync,
  readStatusTenantAsync,
} from "./lifecycle/statuses.js";

export {
  publicDefinition,
  publicVersion,
  publicState,
  publicTransition,
  publicAssignment,
  getDefinitionRow,
  findDefinition,
  getDefinition,
  listDefinitions,
  createDefinition,
  updateDefinition,
  setDefinitionStatus,
  deleteDefinition,
  listVersions,
  createVersion,
  currentVersionRow,
  publishedVersionRow,
  getVersionRow,
  validateDefinitionVersion,
  validateDefinition,
  publishDefinition,
  getStateRow,
  listStates,
  createState,
  updateState,
  deleteState,
  getTransitionRow,
  listTransitions,
  createTransition,
  updateTransition,
  deleteTransition,
  listAssignments,
  createAssignment,
  deleteAssignment,
  resolveAssignment,
  initialStateForVersion,
  stateByCode,
  transitionsFrom,
  readDefinitionTenant,
  getVersionRowAsync,
  resolveAssignmentAsync,
  initialStateForVersionAsync,
  getDefinitionRowAsync,
  findDefinitionAsync,
  getDefinitionAsync,
  listDefinitionsAsync,
  currentVersionRowAsync,
  publishedVersionRowAsync,
  createDefinitionAsync,
  updateDefinitionAsync,
  setDefinitionStatusAsync,
  deleteDefinitionAsync,
  listVersionsAsync,
  createVersionAsync,
  validateDefinitionVersionAsync,
  validateDefinitionAsync,
  publishDefinitionAsync,
  getStateRowAsync,
  listStatesAsync,
  createStateAsync,
  updateStateAsync,
  deleteStateAsync,
  getTransitionRowAsync,
  listTransitionsAsync,
  createTransitionAsync,
  updateTransitionAsync,
  deleteTransitionAsync,
  listAssignmentsAsync,
  createAssignmentAsync,
  deleteAssignmentAsync,
  stateByCodeAsync,
  transitionsFromAsync,
  readDefinitionTenantAsync,
} from "./lifecycle/definitions.js";

export {
  applyInitialLifecycle,
  availableTransitions,
  objectLifecycle,
  transitionObject,
  statusHistory,
  requestObjectRelease,
  objectReleases,
  actorRoleCodes,
  applyInitialLifecycleAsync,
  availableTransitionsAsync,
  objectLifecycleAsync,
  transitionObjectAsync,
  statusHistoryAsync,
  requestObjectReleaseAsync,
  objectReleasesAsync,
  actorRoleCodesAsync,
} from "./lifecycle/engine.js";

export {
  recordStatusHistory,
  applyTransition,
  assignLifecycle,
  conditionContext,
  evaluateGuard,
  recordStatusHistoryAsync,
  applyTransitionAsync,
  assignLifecycleAsync,
} from "./lifecycle/apply.js";

export {
  publicRule,
  publicStep,
  publicApproval,
  publicRelease,
  getRuleRow,
  findRule,
  getRule,
  listRules,
  listReleaseRules,
  listApprovalRules,
  stepsFor,
  createRule,
  updateRule,
  deleteRule,
  resolveRule,
  requestRelease,
  decideApproval,
  resubmit,
  listReleases,
  readRuleTenant,
  getRuleRowAsync,
  findRuleAsync,
  getRuleAsync,
  listRulesAsync,
  listReleaseRulesAsync,
  listApprovalRulesAsync,
  stepsForAsync,
  createRuleAsync,
  updateRuleAsync,
  deleteRuleAsync,
  requestReleaseAsync,
  decideApprovalAsync,
  resubmitAsync,
  listReleasesAsync,
  readRuleTenantAsync,
  publicReleaseAsync,
  decideByReleaseAsync,
} from "./lifecycle/approvals.js";

export {
  registerWorkflowExecutor,
  workflowExecutor,
  resolveApprovers,
  resolveApproversAsync,
  startApproval,
  onApprovalComplete,
} from "./lifecycle/workflow.js";
