// Public facade for the Configuration & Metadata Management module. Business
// modules should depend on this file rather than reaching into the individual
// services, so the internal layout can evolve without breaking consumers.

export {
  DATA_TYPES,
  listAttributes,
  getAttribute,
  createAttribute,
  updateAttribute,
  setAttributeStatus,
  resolveAttribute,
  ancestorAttributes,
  referencedEntity,
  listAttributesAsync,
  getAttributeAsync,
  resolveAttributeAsync,
  ancestorAttributesAsync,
  createAttributeAsync,
  updateAttributeAsync,
  setAttributeStatusAsync,
} from "./metadata/attributes.js";

export {
  TYPE_STATUSES,
  listTypes,
  getType,
  findType,
  createType,
  updateType,
  setTypeStatus,
  deleteType,
  addTypeAttribute,
  updateTypeAttribute,
  removeTypeAttribute,
  effectiveAttributes,
  resolveType,
  ancestorTypes,
  typeTree,
  listTypesAsync,
  getTypeAsync,
  findTypeAsync,
  effectiveAttributesAsync,
  resolveTypeAsync,
  ancestorTypesAsync,
  typeTreeAsync,
  createTypeAsync,
  updateTypeAsync,
  setTypeStatusAsync,
  deleteTypeAsync,
  addTypeAttributeAsync,
  updateTypeAttributeAsync,
  removeTypeAttributeAsync,
} from "./metadata/types.js";

export {
  SELECTION_TYPES,
  listLovs,
  getLov,
  findLov,
  createLov,
  updateLov,
  setLovStatus,
  deleteLov,
  listValues,
  addValue,
  updateValue,
  removeValue,
  cascadeOptions,
  markUsage,
  releaseUsage,
  listUsage,
  assertValueInLov,
  resolveLov,
  listLovsAsync,
  getLovAsync,
  findLovAsync,
  createLovAsync,
  updateLovAsync,
  setLovStatusAsync,
  deleteLovAsync,
  listValuesAsync,
  addValueAsync,
  updateValueAsync,
  removeValueAsync,
  cascadeOptionsAsync,
  listUsageAsync,
  assertValueInLovAsync,
  resolveLovAsync,
} from "./metadata/lovs.js";

export {
  FORM_MODES,
  FORM_STATUSES,
  NODE_KINDS,
  listForms,
  getForm,
  findForm,
  createForm,
  updateForm,
  setFormStatus,
  deleteForm,
  replaceLayout,
  formVersions,
  listFormsAsync,
  getFormAsync,
  findFormAsync,
  createFormAsync,
  updateFormAsync,
  setFormStatusAsync,
  deleteFormAsync,
  replaceLayoutAsync,
  formVersionsAsync,
} from "./metadata/forms.js";

export {
  renderForm,
  renderType,
  formByTypeAndMode,
  renderFormAsync,
  renderTypeAsync,
  formByTypeAndModeAsync,
} from "./metadata/renderer.js";

export {
  RULE_CATEGORIES,
  RULE_STATUSES,
  listRules,
  getRule,
  createRule,
  updateRule,
  setRuleStatus,
  deleteRule,
  rulesFor,
  testRule,
  applyRules,
  listRulesAsync,
  getRuleAsync,
  createRuleAsync,
  updateRuleAsync,
  setRuleStatusAsync,
  deleteRuleAsync,
  rulesForAsync,
  applyRulesAsync,
} from "./metadata/rules.js";

export {
  validateRecord,
  assertValidRecord,
  attributeContract,
  validateRecordAsync,
  assertValidRecordAsync,
  attributeContractAsync,
} from "./metadata/validation.js";
export { evaluate, evaluateValue, validateExpression } from "./metadata/expression.js";

export {
  listVersions,
  getVersion,
  latestVersion,
  recordVersion,
  listVersionsAsync,
  getVersionAsync,
  latestVersionAsync,
  recordVersionAsync,
} from "./metadata/versions.js";

export {
  SCOPES,
  ARTIFACT_TYPES,
  listConfigurations,
  resolveArtifactConfig,
  setConfiguration,
  deleteConfiguration,
  effectiveCatalog,
  assertEnabled,
  listConfigurationsAsync,
  resolveArtifactConfigAsync,
  setConfigurationAsync,
  deleteConfigurationAsync,
  effectiveCatalogAsync,
  assertEnabledAsync,
} from "./metadata/configurations.js";
