// Public facade for the Notification & Communication Framework. Business
// modules (workflow, tasks, lifecycle, ...) should import from this module
// instead of reaching into the internal layout, so the implementation can
// evolve without touching call sites. The primary entry point for producing a
// notification is `publish(db, event)`.

export {
  CHANNELS,
  CHANNEL_LABELS,
  NOTIFICATION_STATUSES,
  OPEN_STATUSES,
  PRIORITIES,
  DELIVERY_MODES,
  FREQUENCIES,
  PROVIDER_TYPES,
  EVENT_STATUSES,
  REMINDER_STATUSES,
  RECIPIENT_TYPES,
  TEMPLATE_ROOTS,
  safeParse,
  assertChannel,
  assertStatus,
  assertPriority,
  assertDeliveryMode,
  assertFrequency,
  assertProviderType,
  normalizeChannels,
  extractVariables,
  validateTemplateVariables,
  escapeHtml,
  resolvePathSafe,
  renderTemplate,
  sanitizeHtml,
  templateHasScript,
  assertTemplateInput,
  evaluateCondition,
  normalizeRecipientDefinition,
  normalizeRecipientItem,
} from "./notifications/validation.js";

export { resolveRecipients, resolveRecipientsAsync } from "./notifications/recipients.js";

export {
  publicTemplate,
  getTemplateRow,
  getTemplateRowAsync,
  findTemplate,
  findTemplateAsync,
  listTemplates,
  listTemplatesAsync,
  createTemplate,
  createTemplateAsync,
  updateTemplate,
  updateTemplateAsync,
  setTemplateStatus,
  setTemplateStatusAsync,
  deleteTemplate,
  deleteTemplateAsync,
  listTemplateVersions,
  listTemplateVersionsAsync,
  sampleContext,
  renderTemplateRow,
  previewTemplate,
  previewTemplateAsync,
  testSendTemplate,
  testSendTemplateAsync,
  findTemplateForEvent,
  findTemplateForEventAsync,
} from "./notifications/templates.js";

export {
  publicRule,
  getRuleRow,
  getRuleRowAsync,
  listRules,
  listRulesAsync,
  createRule,
  createRuleAsync,
  updateRule,
  updateRuleAsync,
  setRuleStatus,
  setRuleStatusAsync,
  deleteRule,
  deleteRuleAsync,
  matchRules,
  matchRulesAsync,
  buildRuleContext,
} from "./notifications/rules.js";

export {
  DEFAULT_PREFERENCES,
  publicPreferences,
  getPreferenceRow,
  getPreferenceRowAsync,
  getPreferences,
  getPreferencesAsync,
  updatePreferences,
  updatePreferencesAsync,
  mandatoryEvents,
  mandatoryEventsAsync,
  ensureDefaultPreferences,
  ensureDefaultPreferencesAsync,
  evaluatePreference,
  evaluatePreferenceAsync,
  isReminderAllowed,
  isReminderAllowedAsync,
  isEscalationAllowed,
  isEscalationAllowedAsync,
} from "./notifications/preferences.js";

export {
  SECRET_KEYS,
  publicProvider,
  getProviderRow,
  getProvider,
  getProviderAsync,
  listProviders,
  listProvidersAsync,
  providerSecrets,
  providerConfig,
  createProvider,
  createProviderAsync,
  updateProvider,
  updateProviderAsync,
  deleteProvider,
  deleteProviderAsync,
  testProvider,
  testProviderAsync,
  providerForChannel,
  ensureDefaultProviders,
} from "./notifications/providers.js";

export {
  BACKOFF_BASE_SECONDS,
  MAX_ATTEMPTS,
  handlerFor,
  enqueue,
  enqueueAsync,
  deliverDirect,
  deliverDirectAsync,
  processQueue,
  processQueueAsync,
  retryDelivery,
  retryDeliveryAsync,
  listDeliveries,
  listDeliveriesAsync,
  deliveryStats,
  deliveryStatsAsync,
} from "./notifications/delivery.js";

export {
  publicEvent,
  publish,
  publishAsync,
  notifyUser,
  notifyUserAsync,
  notifyGroup,
  notifyRole,
  listEvents,
  listEventsAsync,
  getEvent,
  getEventAsync,
  simulateRule,
  simulateRuleAsync,
} from "./notifications/events.js";

export {
  addMinutes,
  scheduleReminder,
  scheduleReminderForRule,
  scheduleReminderForRuleAsync,
  sweepReminders,
  cancelRemindersForObject,
  listReminders,
  listRemindersAsync,
  getReminder,
} from "./notifications/reminders.js";

export {
  publicNotification,
  listInbox,
  listInboxAsync,
  unreadCount,
  unreadCountAsync,
  getNotification,
  getNotificationAsync,
  markRead,
  markReadAsync,
  markUnread,
  markUnreadAsync,
  markAllRead,
  markAllReadAsync,
  archiveNotification,
  archiveNotificationAsync,
  deleteNotification,
  deleteNotificationAsync,
  archiveAllRead,
  archiveAllReadAsync,
  listHistory,
  listHistoryAsync,
} from "./notifications/inbox.js";
