// Public facade for the Object & Relationship Framework. Business modules
// depend on this file (or the platform.js re-exports) rather than the internal
// service layout, so implementation details can evolve safely.

export {
  OBJECT_STATUSES,
  RELATIONSHIP_STATUSES,
  EDGE_STATUSES,
  CARDINALITIES,
  SEMANTICS,
  REFERENCE_TYPES,
  EDGE_DATA_TYPES,
  normalizeEdgeDefinitions,
  validateEdgeValues,
  assertValidEdgeValues,
  normalizeTags,
} from "./objects/validation.js";

export { publicObject, briefObject, briefObjectAsync } from "./objects/repository.js";

export {
  createObject,
  createObjectAsync,
  getObject,
  getObjectAsync,
  listObjects,
  listObjectsAsync,
  updateObject,
  updateObjectAsync,
  setObjectStatus,
  setObjectStatusAsync,
  softDeleteObject,
  softDeleteObjectAsync,
  restoreObject,
  restoreObjectAsync,
  objectTypes,
  objectTypesAsync,
  objectSummary,
  objectSummaryAsync,
  listObjectVersions,
  listObjectVersionsAsync,
  getObjectVersion,
  getObjectVersionAsync,
  recordObjectVersion,
  recordObjectVersionAsync,
  checkoutObject,
  checkoutObjectAsync,
  checkinObject,
  checkinObjectAsync,
  objectLocks,
  objectLocksAsync,
  bulkCreateObjects,
  bulkCreateObjectsAsync,
  bulkMutateObjects,
  bulkMutateObjectsAsync,
} from "./objects/objects.js";

export {
  RELATIONSHIP_TYPE_STATUSES,
  listRelationshipTypes,
  listRelationshipTypesAsync,
  getRelationshipType,
  getRelationshipTypeAsync,
  findRelationshipType,
  findRelationshipTypeAsync,
  createRelationshipType,
  createRelationshipTypeAsync,
  updateRelationshipType,
  updateRelationshipTypeAsync,
  setRelationshipTypeStatus,
  setRelationshipTypeStatusAsync,
  deleteRelationshipType,
  deleteRelationshipTypeAsync,
} from "./objects/relationship-types.js";

export {
  MAX_TRAVERSAL_DEPTH,
  listRelationships,
  listRelationshipsAsync,
  getRelationship,
  getRelationshipAsync,
  createRelationship,
  createRelationshipAsync,
  validateRelationship,
  validateRelationshipAsync,
  updateRelationship,
  updateRelationshipAsync,
  deleteRelationship,
  deleteRelationshipAsync,
  relationshipsForObject,
  relationshipsForObjectAsync,
  traverse,
  traverseAsync,
  graph,
  graphAsync,
  adjacency,
  adjacencyAsync,
} from "./objects/relationships.js";

export {
  listReferences,
  listReferencesAsync,
  getReference,
  getReferenceAsync,
  createReference,
  createReferenceAsync,
  updateReference,
  updateReferenceAsync,
  deleteReference,
  deleteReferenceAsync,
  orphanReferences,
  orphanReferencesAsync,
  directDependencies,
  directDependenciesAsync,
  impactOf,
  impactOfAsync,
  detectCycles,
  detectCyclesAsync,
  safeDeleteReport,
  safeDeleteReportAsync,
} from "./objects/references.js";
