// Public facade for the Workflow & Process Engine. Business modules depend on
// this file (or the platform.js re-exports) rather than the internal services so
// the layout can evolve safely.

import { registerLifecycleExecutor } from "./workflow/lifecycle-bridge.js";

export {
  NODE_TYPES,
  NODE_TYPE_LABELS,
  WORKFLOW_STATUSES,
  VERSION_STATUSES,
  INSTANCE_STATUSES,
  INSTANCE_NODE_STATUSES,
  TASK_STATUSES,
  TASK_OPEN_STATUSES,
  TASK_PRIORITIES,
  ASSIGNEE_TYPES,
  ROUTING_ASSIGNEE_TYPES,
  ROUTING_STRATEGIES,
  APPROVAL_STATUSES,
  APPROVAL_DECISIONS,
  ESCALATION_ACTIONS,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_STATUSES,
  NOTIFICATION_EVENTS,
  BINDING_EVENTS,
  validateGraph,
  assertValidGraph,
  autoLayout,
  evaluateCondition,
  safeParse,
  slugifyKey,
  publicGraph,
} from "./workflow/validation.js";

export {
  publicDefinition,
  publicVersion,
  getDefinitionRow,
  getDefinitionRowAsync,
  findDefinition,
  findDefinitionAsync,
  getDefinition,
  getDefinitionAsync,
  listDefinitions,
  listDefinitionsAsync,
  createDefinition,
  createDefinitionAsync,
  updateDefinition,
  updateDefinitionAsync,
  setDefinitionStatus,
  setDefinitionStatusAsync,
  deleteDefinition,
  deleteDefinitionAsync,
  getVersionRow,
  getVersionRowAsync,
  getVersionByNumber,
  getVersionByNumberAsync,
  publishedVersionRow,
  publishedVersionRowAsync,
  listVersions,
  listVersionsAsync,
  getVersion,
  getVersionAsync,
  createVersion,
  createVersionAsync,
  validateDefinition,
  validateDefinitionAsync,
  publishDefinition,
  publishDefinitionAsync,
  cloneDefinition,
  cloneDefinitionAsync,
  defaultGraph,
  readDefinitionTenant,
} from "./workflow/templates.js";

export {
  designerContext,
  designerContextAsync,
  saveDesignerGraph,
  saveDesignerGraphAsync,
  addNode,
  addNodeAsync,
  patchNode,
  patchNodeAsync,
  removeNode,
  removeNodeAsync,
  addTransition,
  addTransitionAsync,
  patchTransition,
  patchTransitionAsync,
  removeTransition,
  removeTransitionAsync,
  applyAutoLayout,
  applyAutoLayoutAsync,
  validateDesignerGraph,
  validateDesignerGraphAsync,
} from "./workflow/designer.js";

export {
  recordEvent,
  recordEventAsync,
  listEvents,
  listEventsAsync,
  publicEvent,
} from "./workflow/events.js";

export {
  publicRoutingRule,
  getRoutingRuleRow,
  getRoutingRuleRowAsync,
  listRoutingRules,
  listRoutingRulesAsync,
  createRoutingRule,
  createRoutingRuleAsync,
  updateRoutingRule,
  updateRoutingRuleAsync,
  deleteRoutingRule,
  deleteRoutingRuleAsync,
  resolveAssignee,
  resolveAssigneeAsync,
  usersForAssignee,
  usersForAssigneeAsync,
  usersForRole,
  usersForRoleAsync,
  readRoutingTenant,
} from "./workflow/routing.js";

export {
  publicEscalationRule,
  getEscalationRuleRow,
  getEscalationRuleRowAsync,
  listEscalationRules,
  listEscalationRulesAsync,
  createEscalationRule,
  createEscalationRuleAsync,
  updateEscalationRule,
  updateEscalationRuleAsync,
  deleteEscalationRule,
  deleteEscalationRuleAsync,
  applyEscalation,
  applyEscalationAsync,
  sweepEscalations,
  sweepEscalationsAsync,
  readEscalationTenant,
} from "./workflow/escalations.js";

export {
  publicTemplate,
  publicNotification,
  getTemplateRow,
  getTemplateRowAsync,
  findTemplate,
  listTemplates,
  listTemplatesAsync,
  createTemplate,
  createTemplateAsync,
  updateTemplate,
  updateTemplateAsync,
  deleteTemplate,
  deleteTemplateAsync,
  dispatch,
  dispatchAsync,
  renderTemplate,
  sendToAssignees,
  sendToAssigneesAsync,
  listNotifications,
  listNotificationsAsync,
  markNotificationRead,
  markNotificationReadAsync,
  readNotificationTenant,
} from "./workflow/notifications.js";

export {
  publicTask,
  publicSubtask,
  publicComment,
  publicAttachment,
  getTaskRow,
  getTaskRowAsync,
  taskDetail,
  taskDetailAsync,
  listTasks,
  listTasksAsync,
  getTask,
  getTaskAsync,
  createTask,
  completeTask,
  assignTask,
  claimTask,
  updateTaskStatus,
  delegateTask,
  addSubtask,
  updateSubtask,
  deleteSubtask,
  addComment,
  listComments,
  listCommentsAsync,
  addAttachment,
  createTaskAsync,
  completeTaskAsync,
  assignTaskAsync,
  claimTaskAsync,
  updateTaskStatusAsync,
  delegateTaskAsync,
  addSubtaskAsync,
  updateSubtaskAsync,
  deleteSubtaskAsync,
  addCommentAsync,
  addAttachmentAsync,
  listAttachments,
  listAttachmentsAsync,
  listDelegations,
  listDelegationsAsync,
  createDelegation,
  createDelegationAsync,
  revokeDelegation,
  revokeDelegationAsync,
  publicDelegation,
} from "./workflow/tasks.js";

export {
  publicApproval,
  getApprovalRow,
  getApprovalRowAsync,
  resolveApprovalRule,
  createApprovalsForNode,
  listApprovals,
  listApprovalsAsync,
  getApproval,
  getApprovalAsync,
  decideApproval,
  resolveApprovalRuleAsync,
  createApprovalsForNodeAsync,
  decideApprovalAsync,
} from "./workflow/approvals.js";

export {
  publicInstance,
  publicInstanceNode,
  getInstanceRow,
  getInstanceRowAsync,
  listInstances,
  listInstancesAsync,
  getInstance,
  getInstanceAsync,
  startInstance,
  advance,
  pauseInstance,
  resumeInstance,
  cancelInstance,
  retryInstance,
  startInstanceAsync,
  advanceAsync,
  pauseInstanceAsync,
  resumeInstanceAsync,
  cancelInstanceAsync,
  retryInstanceAsync,
  instanceNodes,
  instanceNodesAsync,
  instanceHistory,
  instanceHistoryAsync,
  registerServiceHandler,
  serviceHandler,
} from "./workflow/engine.js";

export {
  publicBinding,
  getBindingRow,
  getBindingRowAsync,
  listBindings,
  listBindingsAsync,
  createBinding,
  createBindingAsync,
  updateBinding,
  updateBindingAsync,
  deleteBinding,
  deleteBindingAsync,
  triggerEvent,
  triggerEventAsync,
  readBindingTenant,
} from "./workflow/bindings.js";

export {
  resolveLifecycleApprovers,
  onLifecycleApprovalComplete,
  onLifecycleApprovalCompleteAsync,
  lifecycleExecutor,
  registerLifecycleExecutor,
} from "./workflow/lifecycle-bridge.js";

registerLifecycleExecutor();
