const TOKEN_KEY = "helix_iam_token";

export function getToken() {
  return localStorage.getItem(TOKEN_KEY);
}

export function setToken(token) {
  if (token) localStorage.setItem(TOKEN_KEY, token);
  else localStorage.removeItem(TOKEN_KEY);
}

export async function api(path, { method = "GET", body } = {}) {
  const headers = { Accept: "application/json" };
  const token = getToken();
  if (token) headers.Authorization = `Bearer ${token}`;
  if (body !== undefined) headers["Content-Type"] = "application/json";
  const res = await fetch(path, {
    method,
    headers,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  let data = null;
  try {
    data = text ? JSON.parse(text) : null;
  } catch {
    data = text;
  }
  if (!res.ok) {
    const err = new Error(data?.error || `Request failed (${res.status})`);
    err.status = res.status;
    err.details = data?.details;
    throw err;
  }
  return data;
}

export const iam = {
  login: (username, password, provider) =>
    api("/api/authentication/login", { method: "POST", body: { username, password, provider } }),
  me: () => api("/api/auth/me"),
  logout: () => api("/api/authentication/logout", { method: "POST" }),
  authProviders: () => api("/api/authentication/providers"),
  authProvidersAdmin: () => api("/api/authentication/providers/admin"),
  createAuthProvider: (body) => api("/api/authentication/providers", { method: "POST", body }),
  updateAuthProvider: (id, body) => api(`/api/authentication/providers/${id}`, { method: "PUT", body }),
  authSettings: () => api("/api/authentication/settings"),
  updateAuthSettings: (body) => api("/api/authentication/settings", { method: "PUT", body }),
  requestPasswordReset: (body) => api("/api/authentication/password-reset/request", { method: "POST", body }),
  completePasswordReset: (body) => api("/api/authentication/password-reset/complete", { method: "POST", body }),
  mySessions: () => api("/api/sessions"),
  revokeSession: (id) => api(`/api/sessions/${id}`, { method: "DELETE" }),
  revokeAllSessions: () => api("/api/sessions/revoke-all", { method: "POST" }),
  adminSessions: (qs) => api(`/api/sessions/admin${qs || ""}`),
  adminRevokeSession: (id) => api(`/api/sessions/admin/${id}`, { method: "DELETE" }),
  mfaStatus: () => api("/api/mfa/status"),
  mfaEnroll: () => api("/api/mfa/totp/enroll", { method: "POST" }),
  mfaVerifyEnroll: (code) => api("/api/mfa/totp/verify", { method: "POST", body: { code } }),
  mfaDisable: (body) => api("/api/mfa/totp/disable", { method: "POST", body }),
  mfaRecovery: (code) => api("/api/mfa/recovery/regenerate", { method: "POST", body: { code } }),
  mfaChallenge: (body) => api("/api/mfa/challenge/verify", { method: "POST", body }),
  adminResetMfa: (userId) => api(`/api/mfa/admin/${userId}/reset`, { method: "POST" }),
  ssoProviders: () => api("/api/sso/providers"),
  ssoStart: (code, body) => api(`/api/sso/${code}/start`, { method: "POST", body }),
  ssoCallback: (code, body) => api(`/api/sso/${code}/callback`, { method: "POST", body }),
  users: (qs) => api(`/api/users${qs || ""}`),
  user: (id) => api(`/api/users/${id}`),
  createUser: (body) => api("/api/users", { method: "POST", body }),
  updateUser: (id, body) => api(`/api/users/${id}`, { method: "PUT", body }),
  activate: (id) => api(`/api/users/${id}/activate`, { method: "POST" }),
  deactivate: (id) => api(`/api/users/${id}/deactivate`, { method: "POST" }),
  lock: (id) => api(`/api/users/${id}/lock`, { method: "POST" }),
  unlock: (id) => api(`/api/users/${id}/unlock`, { method: "POST" }),
  resetPassword: (id, password) =>
    api(`/api/users/${id}/reset-password`, { method: "POST", body: { password } }),
  assignUserRole: (id, roleId, organizationId) =>
    api(`/api/users/${id}/roles`, { method: "POST", body: { roleId, organizationId } }),
  unassignUserRole: (id, roleId, organizationId) =>
    api(`/api/users/${id}/roles/${roleId}?organizationId=${organizationId ?? 0}`, { method: "DELETE" }),
  addUserGroup: (id, groupId) => api(`/api/users/${id}/groups`, { method: "POST", body: { groupId } }),
  removeUserGroup: (id, groupId) => api(`/api/users/${id}/groups/${groupId}`, { method: "DELETE" }),
  groups: (qs) => api(`/api/groups${qs || ""}`),
  group: (id) => api(`/api/groups/${id}`),
  createGroup: (body) => api("/api/groups", { method: "POST", body }),
  updateGroup: (id, body) => api(`/api/groups/${id}`, { method: "PUT", body }),
  deleteGroup: (id) => api(`/api/groups/${id}`, { method: "DELETE" }),
  addMember: (id, userId) => api(`/api/groups/${id}/members`, { method: "POST", body: { userId } }),
  removeMember: (id, userId) => api(`/api/groups/${id}/members/${userId}`, { method: "DELETE" }),
  assignGroupRole: (id, roleId, organizationId) =>
    api(`/api/groups/${id}/roles`, { method: "POST", body: { roleId, organizationId } }),
  unassignGroupRole: (id, roleId, organizationId) =>
    api(`/api/groups/${id}/roles/${roleId}?organizationId=${organizationId ?? 0}`, { method: "DELETE" }),
  roles: (qs) => api(`/api/roles${qs || ""}`),
  role: (id) => api(`/api/roles/${id}`),
  createRole: (body) => api("/api/roles", { method: "POST", body }),
  updateRole: (id, body) => api(`/api/roles/${id}`, { method: "PUT", body }),
  deleteRole: (id) => api(`/api/roles/${id}`, { method: "DELETE" }),
  orgs: (qs) => api(`/api/organizations${qs || ""}`),
  organization: (id) => api(`/api/organizations/${id}`),
  createOrganization: (body) => api("/api/organizations", { method: "POST", body }),
  updateOrganization: (id, body) => api(`/api/organizations/${id}`, { method: "PUT", body }),
  deleteOrganization: (id) => api(`/api/organizations/${id}`, { method: "DELETE" }),
  activateOrganization: (id) => api(`/api/organizations/${id}/activate`, { method: "POST" }),
  deactivateOrganization: (id) => api(`/api/organizations/${id}/deactivate`, { method: "POST" }),
  orgTree: (qs) => api(`/api/organizations/tree${qs || ""}`),
  orgSites: (id) => api(`/api/organizations/${id}/sites`),
  createSite: (id, body) => api(`/api/organizations/${id}/sites`, { method: "POST", body }),
  moveOrganization: (id, parent_id) =>
    api(`/api/organizations/${id}/move`, { method: "POST", body: { parent_id } }),
  orgMembers: (id) => api(`/api/organizations/${id}/members`),
  addOrgMember: (id, body) => api(`/api/organizations/${id}/members`, { method: "POST", body }),
  removeOrgMember: (id, userId) => api(`/api/organizations/${id}/members/${userId}`, { method: "DELETE" }),
  orgContext: (id) => api(`/api/organizations/${id}/context`),
  companies: (qs) => api(`/api/companies${qs || ""}`),
  businessUnits: (qs) => api(`/api/business-units${qs || ""}`),
  plants: (qs) => api(`/api/plants${qs || ""}`),
  sites: (qs) => api(`/api/sites${qs || ""}`),
  departments: (qs) => api(`/api/departments${qs || ""}`),
  userOrganizations: (id) => api(`/api/users/${id}/organizations`),
  addUserOrganization: (id, body) => api(`/api/users/${id}/organizations`, { method: "POST", body }),
  removeUserOrganization: (id, orgId) => api(`/api/users/${id}/organizations/${orgId}`, { method: "DELETE" }),
  hierarchy: () => api("/api/hierarchy"),
  platformHierarchy: () => api("/api/platform/hierarchy"),
  updatePlatformHierarchy: (body) => api("/api/platform/hierarchy", { method: "PUT", body }),
  platformSettings: () => api("/api/platform/settings"),
  updatePlatformSettings: (body) => api("/api/platform/settings", { method: "PUT", body }),
  policy: () => api("/api/password-policy"),
  updatePolicy: (body) => api("/api/password-policy", { method: "PUT", body }),
  audit: (qs) => api(`/api/audit-logs${qs || ""}`),
  access: (userId) => api(`/api/iam/principals/${userId}/access`),
  applications: () => api("/api/applications"),
  createApplication: (body) => api("/api/applications", { method: "POST", body }),
  resources: (qs) => api(`/api/resources${qs || ""}`),
  createResource: (body) => api("/api/resources", { method: "POST", body }),
  permissions: (qs) => api(`/api/permissions${qs || ""}`),
  createPermission: (body) => api("/api/permissions", { method: "POST", body }),
  deletePermission: (id) => api(`/api/permissions/${id}`, { method: "DELETE" }),
  permissionMatrix: (qs) => api(`/api/permissions/matrix${qs || ""}`),
  rolePermissions: (id) => api(`/api/roles/${id}/permissions`),
  grantRolePermission: (id, body) => api(`/api/roles/${id}/permissions`, { method: "POST", body }),
  revokeRolePermission: (id, permissionId, organizationId) =>
    api(`/api/roles/${id}/permissions/${permissionId}?organizationId=${organizationId ?? 0}`, {
      method: "DELETE",
    }),
  tenants: (qs) => api(`/api/tenants${qs || ""}`),
  tenant: (id) => api(`/api/tenants/${id}`),
  createTenant: (body) => api("/api/tenants", { method: "POST", body }),
  updateTenant: (id, body) => api(`/api/tenants/${id}`, { method: "PUT", body }),
  activateTenant: (id) => api(`/api/tenants/${id}/activate`, { method: "POST" }),
  deactivateTenant: (id) => api(`/api/tenants/${id}/deactivate`, { method: "POST" }),
  deleteTenant: (id) => api(`/api/tenants/${id}`, { method: "DELETE" }),
  selectTenant: (id) => api(`/api/tenants/${id}/select`, { method: "POST" }),
  tenantContext: (id) => api(`/api/tenants/${id}/context`),
  tenantConfig: (id) => api(`/api/tenants/${id}/config`),
  updateTenantConfig: (id, values) =>
    api(`/api/tenants/${id}/config`, { method: "PUT", body: { values } }),
  config: (qs) => api(`/api/config${qs || ""}`),
  updateConfig: (body) => api("/api/config", { method: "PUT", body }),
  checkPermission: (body) => api("/api/authorization/check", { method: "POST", body }),
  effectivePermissions: (userId, qs) => api(`/api/authorization/effective/${userId}${qs || ""}`),
};

export const metadata = {
  types: (qs) => api(`/api/metadata/types${qs || ""}`),
  typeTree: (qs) => api(`/api/metadata/types/tree${qs || ""}`),
  type: (id) => api(`/api/metadata/types/${id}`),
  resolveType: (id) => api(`/api/metadata/types/${id}/resolve`),
  typeContract: (id) => api(`/api/metadata/types/${id}/contract`),
  createType: (body) => api("/api/metadata/types", { method: "POST", body }),
  updateType: (id, body) => api(`/api/metadata/types/${id}`, { method: "PUT", body }),
  deleteType: (id) => api(`/api/metadata/types/${id}`, { method: "DELETE" }),
  setTypeStatus: (id, status) => api(`/api/metadata/types/${id}/status`, { method: "POST", body: { status } }),
  attachAttribute: (id, body) => api(`/api/metadata/types/${id}/attributes`, { method: "POST", body }),
  updateTypeAttribute: (id, attributeId, body) =>
    api(`/api/metadata/types/${id}/attributes/${attributeId}`, { method: "PUT", body }),
  detachAttribute: (id, attributeId) =>
    api(`/api/metadata/types/${id}/attributes/${attributeId}`, { method: "DELETE" }),
  attributes: (qs) => api(`/api/metadata/attributes${qs || ""}`),
  attribute: (id) => api(`/api/metadata/attributes/${id}`),
  createAttribute: (body) => api("/api/metadata/attributes", { method: "POST", body }),
  updateAttribute: (id, body) => api(`/api/metadata/attributes/${id}`, { method: "PUT", body }),
  deleteAttribute: (id) => api(`/api/metadata/attributes/${id}`, { method: "DELETE" }),
  setAttributeStatus: (id, status) =>
    api(`/api/metadata/attributes/${id}/status`, { method: "POST", body: { status } }),
  lovs: (qs) => api(`/api/metadata/lovs${qs || ""}`),
  lov: (id) => api(`/api/metadata/lovs/${id}`),
  createLov: (body) => api("/api/metadata/lovs", { method: "POST", body }),
  updateLov: (id, body) => api(`/api/metadata/lovs/${id}`, { method: "PUT", body }),
  deleteLov: (id) => api(`/api/metadata/lovs/${id}`, { method: "DELETE" }),
  setLovStatus: (id, status) => api(`/api/metadata/lovs/${id}/status`, { method: "POST", body: { status } }),
  addLovValue: (id, body) => api(`/api/metadata/lovs/${id}/values`, { method: "POST", body }),
  updateLovValue: (id, valueId, body) =>
    api(`/api/metadata/lovs/${id}/values/${valueId}`, { method: "PUT", body }),
  removeLovValue: (id, valueId) => api(`/api/metadata/lovs/${id}/values/${valueId}`, { method: "DELETE" }),
  cascadeOptions: (id, qs) => api(`/api/metadata/lovs/${id}/cascade${qs || ""}`),
  forms: (qs) => api(`/api/metadata/forms${qs || ""}`),
  form: (id) => api(`/api/metadata/forms/${id}`),
  createForm: (body) => api("/api/metadata/forms", { method: "POST", body }),
  updateForm: (id, body) => api(`/api/metadata/forms/${id}`, { method: "PUT", body }),
  deleteForm: (id) => api(`/api/metadata/forms/${id}`, { method: "DELETE" }),
  setFormStatus: (id, status) => api(`/api/metadata/forms/${id}/status`, { method: "POST", body: { status } }),
  replaceLayout: (id, body) => api(`/api/metadata/forms/${id}/layout`, { method: "PUT", body }),
  formVersions: (id) => api(`/api/metadata/forms/${id}/versions`),
  renderForm: (id, body) => api(`/api/metadata/forms/${id}/render`, { method: "POST", body }),
  rules: (qs) => api(`/api/metadata/rules${qs || ""}`),
  rule: (id) => api(`/api/metadata/rules/${id}`),
  createRule: (body) => api("/api/metadata/rules", { method: "POST", body }),
  updateRule: (id, body) => api(`/api/metadata/rules/${id}`, { method: "PUT", body }),
  deleteRule: (id) => api(`/api/metadata/rules/${id}`, { method: "DELETE" }),
  setRuleStatus: (id, status) => api(`/api/metadata/rules/${id}/status`, { method: "POST", body: { status } }),
  testRule: (id, context) => api(`/api/metadata/rules/${id}/test`, { method: "POST", body: { context } }),
  validate: (body) => api("/api/metadata/validate", { method: "POST", body }),
  configurations: (qs) => api(`/api/metadata/configurations${qs || ""}`),
  effectiveCatalog: (qs) => api(`/api/metadata/configurations/effective${qs || ""}`),
  setConfiguration: (body) => api("/api/metadata/configurations", { method: "POST", body }),
  deleteConfiguration: (body) => api("/api/metadata/configurations", { method: "DELETE", body }),
};

export const objects = {
  types: () => api("/api/object-types"),
  typeForm: (id, qs) => api(`/api/object-types/${id}/form${qs || ""}`),
  list: (qs) => api(`/api/objects${qs || ""}`),
  summary: () => api("/api/objects/summary"),
  get: (id) => api(`/api/objects/${id}`),
  create: (body) => api("/api/objects", { method: "POST", body }),
  update: (id, body) => api(`/api/objects/${id}`, { method: "PUT", body }),
  remove: (id, force) => api(`/api/objects/${id}${force ? "?force=true" : ""}`, { method: "DELETE" }),
  restore: (id) => api(`/api/objects/${id}/restore`, { method: "POST" }),
  setStatus: (id, status) => api(`/api/objects/${id}/status`, { method: "POST", body: { status } }),
  checkout: (id, body) => api(`/api/objects/${id}/checkout`, { method: "POST", body }),
  checkin: (id, body) => api(`/api/objects/${id}/checkin`, { method: "POST", body }),
  locks: (id) => api(`/api/objects/${id}/locks`),
  versions: (id, qs) => api(`/api/objects/${id}/versions${qs || ""}`),
  version: (id, revision) => api(`/api/objects/${id}/versions/${revision}`),
  relationships: (id, qs) => api(`/api/objects/${id}/relationships${qs || ""}`),
  tree: (id, qs) => api(`/api/objects/${id}/tree${qs || ""}`),
  graph: (id, qs) => api(`/api/objects/${id}/graph${qs || ""}`),
  dependencies: (id) => api(`/api/objects/${id}/dependencies`),
  safeDelete: (id) => api(`/api/objects/${id}/safe-delete`),
  relationshipTypes: (qs) => api(`/api/relationship-types${qs || ""}`),
  relationshipType: (id) => api(`/api/relationship-types/${id}`),
  createRelationshipType: (body) => api("/api/relationship-types", { method: "POST", body }),
  updateRelationshipType: (id, body) => api(`/api/relationship-types/${id}`, { method: "PUT", body }),
  setRelationshipTypeStatus: (id, status) =>
    api(`/api/relationship-types/${id}/status`, { method: "POST", body: { status } }),
  deleteRelationshipType: (id) => api(`/api/relationship-types/${id}`, { method: "DELETE" }),
  relationshipsList: (qs) => api(`/api/relationships${qs || ""}`),
  createRelationship: (body) => api("/api/relationships", { method: "POST", body }),
  validateRelationship: (body) => api("/api/relationships/validate", { method: "POST", body }),
  deleteRelationship: (id, force) =>
    api(`/api/relationships/${id}${force ? "?force=true" : ""}`, { method: "DELETE" }),
  references: (qs) => api(`/api/references${qs || ""}`),
  referencesOrphans: () => api("/api/references/orphans"),
  createReference: (body) => api("/api/references", { method: "POST", body }),
  deleteReference: (id) => api(`/api/references/${id}`, { method: "DELETE" }),
  impact: (objectId, qs) => api(`/api/dependencies/impact?objectId=${objectId}${qs ? `&${qs}` : ""}`),
  cycles: () => api("/api/dependencies/cycles"),
  lifecycle: (id) => api(`/api/objects/${id}/lifecycle`),
  transitions: (id) => api(`/api/objects/${id}/transitions`),
  transition: (id, body) => api(`/api/objects/${id}/transitions`, { method: "POST", body }),
  statusHistory: (id, qs) => api(`/api/objects/${id}/status-history${qs || ""}`),
  releases: (id, qs) => api(`/api/objects/${id}/releases${qs || ""}`),
  requestRelease: (id, body) => api(`/api/objects/${id}/release`, { method: "POST", body }),
  decideApproval: (id, approvalId, body) =>
    api(`/api/objects/${id}/approvals/${approvalId}`, { method: "POST", body }),
};

export const workflow = {
  templates: (qs) => api(`/api/workflow-templates${qs || ""}`),
  template: (id) => api(`/api/workflow-templates/${id}`),
  createTemplate: (body) => api("/api/workflow-templates", { method: "POST", body }),
  updateTemplate: (id, body) => api(`/api/workflow-templates/${id}`, { method: "PUT", body }),
  setTemplateStatus: (id, status) => api(`/api/workflow-templates/${id}/status`, { method: "POST", body: { status } }),
  deleteTemplate: (id) => api(`/api/workflow-templates/${id}`, { method: "DELETE" }),
  versions: (id) => api(`/api/workflow-templates/${id}/versions`),
  createVersion: (id, body) => api(`/api/workflow-templates/${id}/versions`, { method: "POST", body: body || {} }),
  version: (id, version) => api(`/api/workflow-templates/${id}/versions/${version}`),
  validate: (id, body) => api(`/api/workflow-templates/${id}/validate`, { method: "POST", body: body || {} }),
  publish: (id, body) => api(`/api/workflow-templates/${id}/publish`, { method: "POST", body: body || {} }),
  clone: (id, body) => api(`/api/workflow-templates/${id}/clone`, { method: "POST", body: body || {} }),
  designer: (id, qs) => api(`/api/workflow-templates/${id}/designer${qs || ""}`),
  saveDesigner: (id, body) => api(`/api/workflow-templates/${id}/designer`, { method: "PUT", body }),
  autoLayout: (id, body) => api(`/api/workflow-templates/${id}/designer/auto-layout`, { method: "POST", body: body || {} }),
  validateDesigner: (id, body) => api(`/api/workflow-templates/${id}/designer/validate`, { method: "POST", body: body || {} }),
  instances: (qs) => api(`/api/workflow-instances${qs || ""}`),
  instance: (id) => api(`/api/workflow-instances/${id}`),
  startInstance: (body) => api("/api/workflow-instances", { method: "POST", body }),
  instanceNodes: (id) => api(`/api/workflow-instances/${id}/nodes`),
  instanceHistory: (id, qs) => api(`/api/workflow-instances/${id}/history${qs || ""}`),
  cancelInstance: (id, body) => api(`/api/workflow-instances/${id}/cancel`, { method: "POST", body: body || {} }),
  pauseInstance: (id) => api(`/api/workflow-instances/${id}/pause`, { method: "POST", body: {} }),
  resumeInstance: (id) => api(`/api/workflow-instances/${id}/resume`, { method: "POST", body: {} }),
  retryInstance: (id, body) => api(`/api/workflow-instances/${id}/retry`, { method: "POST", body: body || {} }),
  tasks: (qs) => api(`/api/tasks${qs || ""}`),
  task: (id) => api(`/api/tasks/${id}`),
  completeTask: (id, body) => api(`/api/tasks/${id}/complete`, { method: "POST", body: body || {} }),
  assignTask: (id, body) => api(`/api/tasks/${id}/assign`, { method: "POST", body }),
  claimTask: (id) => api(`/api/tasks/${id}/claim`, { method: "POST", body: {} }),
  setTaskStatus: (id, status) => api(`/api/tasks/${id}/status`, { method: "POST", body: { status } }),
  comments: (id) => api(`/api/tasks/${id}/comments`),
  addComment: (id, body) => api(`/api/tasks/${id}/comments`, { method: "POST", body }),
  attachments: (id) => api(`/api/tasks/${id}/attachments`),
  addAttachment: (id, body) => api(`/api/tasks/${id}/attachments`, { method: "POST", body }),
  addSubtask: (id, body) => api(`/api/tasks/${id}/subtasks`, { method: "POST", body }),
  updateSubtask: (id, subtaskId, body) => api(`/api/tasks/${id}/subtasks/${subtaskId}`, { method: "PATCH", body }),
  deleteSubtask: (id, subtaskId) => api(`/api/tasks/${id}/subtasks/${subtaskId}`, { method: "DELETE" }),
  approvals: (qs) => api(`/api/workflow-approvals${qs || ""}`),
  approval: (id) => api(`/api/workflow-approvals/${id}`),
  decideApproval: (id, body) => api(`/api/workflow-approvals/${id}/decision`, { method: "POST", body }),
  routingRules: (qs) => api(`/api/workflow-routing-rules${qs || ""}`),
  createRoutingRule: (body) => api("/api/workflow-routing-rules", { method: "POST", body }),
  escalationRules: (qs) => api(`/api/workflow-escalation-rules${qs || ""}`),
  createEscalationRule: (body) => api("/api/workflow-escalation-rules", { method: "POST", body }),
  sweepEscalations: () => api("/api/workflow-escalations/sweep", { method: "POST", body: {} }),
  notifications: (qs) => api(`/api/workflow-notifications${qs || ""}`),
  readNotification: (id) => api(`/api/workflow-notifications/${id}/read`, { method: "POST", body: {} }),
  notificationTemplates: (qs) => api(`/api/workflow-notification-templates${qs || ""}`),
  createNotificationTemplate: (body) => api("/api/workflow-notification-templates", { method: "POST", body }),
  bindings: (qs) => api(`/api/workflow-bindings${qs || ""}`),
  createBinding: (body) => api("/api/workflow-bindings", { method: "POST", body }),
  delegations: (qs) => api(`/api/workflow-delegations${qs || ""}`),
  createDelegation: (body) => api("/api/workflow-delegations", { method: "POST", body }),
  revokeDelegation: (id) => api(`/api/workflow-delegations/${id}`, { method: "DELETE" }),
  nodeTypes: () => Promise.resolve({ items: [
    "start", "end", "task", "approval", "decision", "parallel", "join", "notification", "timer", "subprocess", "service", "terminate",
  ] }),
};

export const lifecycle = {
  statuses: (qs) => api(`/api/statuses${qs || ""}`),
  status: (id) => api(`/api/statuses/${id}`),
  createStatus: (body) => api("/api/statuses", { method: "POST", body }),
  updateStatus: (id, body) => api(`/api/statuses/${id}`, { method: "PUT", body }),
  deleteStatus: (id) => api(`/api/statuses/${id}`, { method: "DELETE" }),
  definitions: (qs) => api(`/api/lifecycle-definitions${qs || ""}`),
  definition: (id) => api(`/api/lifecycle-definitions/${id}`),
  get: (id) => api(`/api/lifecycle-definitions/${id}`),
  createDefinition: (body) => api("/api/lifecycle-definitions", { method: "POST", body }),
  updateDefinition: (id, body) => api(`/api/lifecycle-definitions/${id}`, { method: "PUT", body }),
  versions: (id) => api(`/api/lifecycle-definitions/${id}/versions`),
  validate: (id, qs) => api(`/api/lifecycle-definitions/${id}/validate${qs || ""}`),
  publish: (id, body) => api(`/api/lifecycle-definitions/${id}/publish`, { method: "POST", body }),
  states: (qs) => api(`/api/lifecycle-states${qs || ""}`),
  createState: (body) => api("/api/lifecycle-states", { method: "POST", body }),
  transitions: (qs) => api(`/api/lifecycle-transitions${qs || ""}`),
  createTransition: (body) => api("/api/lifecycle-transitions", { method: "POST", body }),
  assignments: (qs) => api(`/api/lifecycle-assignments${qs || ""}`),
  createAssignment: (body) => api("/api/lifecycle-assignments", { method: "POST", body }),
  releaseRules: (qs) => api(`/api/release-rules${qs || ""}`),
  approvalRules: (qs) => api(`/api/approval-rules${qs || ""}`),
  createApprovalRule: (body) => api("/api/approval-rules", { method: "POST", body }),
  createReleaseRule: (body) => api("/api/release-rules", { method: "POST", body }),
};

