process.env.FILE_STORAGE_PROVIDER = "memory";

// End-to-end acceptance test for the Requirement -> Manufacturing traceability
// layer. It builds the full chain (Requirement -> EBOM -> MBOM -> BOP ->
// Operation -> Work center, CTQ) using only the existing PDM/BOM/Object/
// Classification engines plus this layer's composition seams, then asserts the
// projections (matrix, coverage, gaps, impact, navigation) and the REST surface
// that the frontend workspace consumes.
import { test, describe, before, after } from "node:test";
import assert from "node:assert/strict";
import http from "node:http";
import { migrate, queryOne, openTestDatabase } from "../db.js";
import { seedDatabase } from "../seed.js";
import { createApp } from "../app.js";
import { ensureNumberingFoundation } from "../services/numbering.js";
import { RequirementsManager, ensureRequirementsFoundation } from "../services/requirements/index.js";
import { ensureRequirementObject } from "../services/requirement-pdm/index.js";
import {
  Definitions as BomDefinitions,
  Revisions as BomRevisions,
  Lines as BomLines,
  Transformation as BomTransformation,
  Seed as BomSeed,
  Configuration as BomConfiguration,
  ensureBomFoundation,
} from "../services/bom/index.js";
import { createObject } from "../services/objects.js";
import { Characteristics } from "../services/classification/index.js";
import {
  ensureRequirementManufacturingFoundation,
  createManufacturingObject,
  createAllocation,
  designateCtq,
  addOperationToBop,
  linkOperationToWorkCenter,
  linkOperationToMbomItem,
  manufacturingMatrix,
  manufacturingGaps,
  manufacturingCoverage,
  manufacturingTrace,
  ebomMbomMappings,
  requirementCtqs,
  analyzeRequirementImpact,
  analyzeNodeImpact,
  submitGapSweep,
} from "../services/requirement-manufacturing/index.js";

const IP = "127.0.0.1";

function listen(app) {
  return new Promise((resolve) => {
    const server = http.createServer(app);
    server.listen(0, "127.0.0.1", () => resolve({ server, port: server.address().port }));
  });
}

function request(port, method, path, { token, body } = {}) {
  return new Promise((resolve, reject) => {
    const payload = body ? JSON.stringify(body) : null;
    const req = http.request(
      {
        hostname: "127.0.0.1",
        port,
        path,
        method,
        headers: {
          ...(payload !== null ? { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(payload) } : {}),
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
      },
      (res) => {
        const chunks = [];
        res.on("data", (c) => chunks.push(c));
        res.on("end", () => {
          const text = Buffer.concat(chunks).toString("utf8");
          let parsed = text;
          try {
            parsed = text ? JSON.parse(text) : null;
          } catch {
            parsed = text;
          }
          resolve({ status: res.statusCode, body: parsed, text });
        });
      }
    );
    req.on("error", reject);
    if (payload !== null) req.write(payload);
    req.end();
  });
}

describe("Requirement -> Manufacturing end-to-end acceptance", () => {
  let db;
  let server;
  let port;
  let adminToken;
  let tenant;
  let actor;
  let requirement;
  let ebomRevision;
  let mbomRevision;
  let bopRevision;
  let operation;
  let workCenter;
  let ctq;

  before(async () => {
    db = openTestDatabase();
    migrate(db);
    seedDatabase(db);
    ensureNumberingFoundation(db);
    ensureRequirementsFoundation(db);
    ensureBomFoundation(db);
    ensureRequirementManufacturingFoundation(db);

    tenant = queryOne(db, "SELECT id FROM organizations WHERE code = 'helix'").id;
    actor = queryOne(db, "SELECT id, username FROM users WHERE username = 'admin'");

    // Real EBOM -> MBOM provenance generated by the BOM transformation engine.
    BomConfiguration.ensureBomConfig(db, tenant);
    BomSeed.seedBom(db, tenant);
    const ebom = BomDefinitions.getBom(db, tenant, "DEMO-EBOM-PUMP");
    ebomRevision = BomRevisions.listRevisions(db, { tenantId: tenant, bomId: ebom.id }).items[0];
    const definition = BomTransformation.listTransformationDefinitions(db, { tenantId: tenant }).items[0];
    const executed = BomTransformation.transform(db, tenant, { definition_id: definition.id, source_revision_id: ebomRevision.id, mode: "EXECUTE" });
    mbomRevision = BomRevisions.getRevision(db, tenant, executed.run.target_revision_id);

    // Requirement mirrored as a first-class Object so the Digital Thread can
    // resolve it, then allocated across the manufacturing chain.
    requirement = RequirementsManager.createRequirement(db, tenant, { title: "E2E requirement", requirement_type: "business_requirement", criticality: "HIGH" }, actor, IP);
    ensureRequirementObject(db, tenant, requirement, actor, IP);
    requirement = queryOne(db, "SELECT * FROM requirements WHERE id = ?", [requirement.id]);

    createAllocation(db, tenant, { requirement_id: String(requirement.id), target_type: "bom_revision", relationship_type: "IMPLEMENTED_BY", target_id: String(ebomRevision.id) }, actor, IP);
    createAllocation(db, tenant, { requirement_id: String(requirement.id), target_type: "bom_revision", relationship_type: "IMPLEMENTED_BY", target_id: String(mbomRevision.id) }, actor, IP);

    // BOP with operations, work center, precedence and an MBOM item consumer.
    const bop = BomDefinitions.createBom(db, tenant, { bom_number: "E2E-BOP", name: "Process plan", bom_type: "BOP" }, actor, IP);
    bopRevision = BomRevisions.createRevision(db, tenant, bop.id, { revision_number: "A1" }, actor, IP);
    operation = createManufacturingObject(db, tenant, { object_type: "operation", code: "E2E-OP-10", name: "Weld" }, actor, IP);
    workCenter = createManufacturingObject(db, tenant, { object_type: "work_center", code: "E2E-WC-10", name: "Line 1" }, actor, IP);
    addOperationToBop(db, tenant, bopRevision.id, { operation_id: operation.id, sequence: 10 }, actor, IP);
    linkOperationToWorkCenter(db, tenant, operation.id, { work_center_id: workCenter.id }, actor, IP);

    const part = createObject(db, { type: "part", code: "E2E-PART", name: "Housing", status: "released", data: { "part.number": "E2E-PART", "part.name": "Housing", "part.category": "mechanical", "part.status": "released" } }, actor, tenant, IP);
    BomLines.addLine(db, tenant, mbomRevision.id, { child_object_id: String(part.id), child_object_type: "part", quantity: 1, uom: "EA", find_number: "10" }, actor, IP);
    linkOperationToMbomItem(db, tenant, operation.id, { mbom_item_id: part.id }, actor, IP);

    createAllocation(db, tenant, { requirement_id: String(requirement.id), target_type: "bom_revision", relationship_type: "SATISFIED_BY", target_id: String(bopRevision.id) }, actor, IP);
    createAllocation(db, tenant, { requirement_id: String(requirement.id), target_type: "operation", relationship_type: "REALIZED_BY", target_id: String(operation.id) }, actor, IP);
    createAllocation(db, tenant, { requirement_id: String(requirement.id), target_type: "work_center", relationship_type: "SATISFIED_BY", target_id: String(workCenter.id) }, actor, IP);

    ctq = Characteristics.createCharacteristic(db, tenant, { code: "E2E-CTQ", name: "Weld depth", data_type: "UNIT_NUMERIC", unit: "MM" }, actor, IP);
    designateCtq(db, tenant, ctq.id, { ctq: true, severity: "HIGH" }, actor, IP);
    createAllocation(db, tenant, { requirement_id: String(requirement.id), target_type: "characteristic", relationship_type: "CONTROLLED_BY", target_id: String(ctq.id) }, actor, IP);

    const started = await listen(createApp(db));
    server = started.server;
    port = started.port;
    adminToken = (await request(port, "POST", "/api/auth/login", { body: { username: "admin", password: "HelixAdmin!42" } })).body.token;
  });

  after(() => {
    server?.close();
    db?.close();
  });

  test("projects a COVERED matrix row across the full manufacturing chain", () => {
    const matrix = manufacturingMatrix(db, tenant, { pageSize: 500 });
    const row = matrix.items.find((item) => item.requirement.requirement_id === requirement.id);
    assert.ok(row, "requirement must appear in the matrix");
    assert.equal(row.coverage_status, "COVERED");
    assert.ok(row.counts.ebom >= 1, "EBOM allocated");
    assert.ok(row.counts.mbom >= 1, "MBOM allocated");
    assert.ok(row.counts.bop >= 1, "BOP allocated");
    assert.ok(row.counts.operation >= 1, "operation allocated");
    assert.ok(row.counts.work_center >= 1, "work center allocated");
    assert.ok(row.counts.ctq >= 1, "CTQ allocated");
    assert.ok(row.rule_results.every((rule) => rule.met), "all enabled rules met");
  });

  test("reports zero scoped gaps for a fully covered requirement", () => {
    const gaps = manufacturingGaps(db, tenant, { requirementId: requirement.id, pageSize: 500 });
    assert.equal(gaps.total, 0);
    assert.equal(gaps.items.length, 0);
  });

  test("traces requirement -> operation -> work center forward", () => {
    const trace = manufacturingTrace(db, tenant, { objectType: "requirement", objectId: requirement.object_id, direction: "forward", maxDepth: 8 }, actor);
    const keys = trace.nodes.map((node) => `${node.object_type}:${node.object_id}`);
    assert.ok(keys.includes(`requirement:${requirement.object_id}`));
    assert.ok(keys.includes(`operation:${operation.id}`));
    assert.ok(keys.includes(`work_center:${workCenter.id}`));
  });

  test("links the requirement's CTQ to the operation", () => {
    const ctqs = requirementCtqs(db, tenant, requirement.requirement_ref);
    assert.ok(ctqs.total >= 1);
    assert.ok(ctqs.items.some((item) => String(item.characteristic.characteristic_id) === String(ctq.id)));
  });

  test("analyzes downstream requirement impact with manufacturing categories", () => {
    const impact = analyzeRequirementImpact(db, tenant, requirement.requirement_ref, { maxDepth: 8 }, actor, IP);
    assert.ok(impact.impacted_count >= 1);
    assert.equal(impact.requirement.id, requirement.id);
    assert.ok(impact.category_totals.PROCESS >= 1, "operation classified as PROCESS");
    assert.ok(impact.category_totals.CTQ >= 1 || impact.category_totals.CHARACTERISTIC >= 1);
    assert.equal(impact.items.some((item) => item.object_type === "operation"), true);
  });

  test("reverse node impact maps an operation back to its requirement", () => {
    const nodeImpact = analyzeNodeImpact(db, tenant, { nodeType: "operation", nodeId: operation.id }, {}, actor, IP);
    assert.equal(nodeImpact.requirement_count, 1);
    assert.equal(nodeImpact.requirements[0].requirement_id, requirement.id);
    assert.ok(nodeImpact.impacted_count >= 1);
  });

  test("EBOM -> MBOM mappings are projected from transformation provenance", () => {
    const mappings = ebomMbomMappings(db, tenant, ebomRevision.id, { pageSize: 500 });
    assert.ok(mappings.summary.mappings >= 1);
    assert.equal(mappings.summary.invalid, 0);
  });

  test("aggregate coverage reflects full coverage of the requirement", () => {
    const coverage = manufacturingCoverage(db, tenant);
    assert.ok(coverage.requirements.requirements >= 1);
    assert.equal(typeof coverage.overall_coverage, "number");
    assert.ok(coverage.ctq.total >= 1);
  });

  test("submits a scoped gap sweep job", () => {
    const job = submitGapSweep(db, tenant, { requirement_id: requirement.requirement_ref }, actor, IP);
    assert.ok(job.job || job.job_ref || job.id, "a job handle is returned");
  });

  test("serves the frontend API surface end to end", async () => {
    const matrix = await request(port, "GET", `/api/v1/requirement-manufacturing/matrix?requirement_id=${requirement.id}`, { token: adminToken });
    assert.equal(matrix.status, 200);
    assert.equal(matrix.body.items[0].coverage_status, "COVERED");

    const coverage = await request(port, "GET", "/api/v1/requirement-manufacturing/coverage", { token: adminToken });
    assert.equal(coverage.status, 200);

    const gaps = await request(port, "GET", `/api/v1/requirement-manufacturing/requirements/${requirement.requirement_ref}/gaps`, { token: adminToken });
    assert.equal(gaps.status, 200);
    assert.equal(gaps.body.total, 0);

    const impact = await request(port, "POST", "/api/v1/requirement-manufacturing/impact-analysis", { token: adminToken, body: { requirement_ref: requirement.requirement_ref } });
    assert.equal(impact.status, 200);
    assert.equal(impact.body.requirement.id, requirement.id);

    const nodeImpact = await request(port, "POST", "/api/v1/requirement-manufacturing/node-impact", { token: adminToken, body: { node_type: "operation", node_id: operation.id } });
    assert.equal(nodeImpact.status, 200);
    assert.equal(nodeImpact.body.requirement_count, 1);

    const trace = await request(port, "GET", `/api/v1/requirement-manufacturing/trace?object_type=requirement&object_id=${requirement.object_id}&direction=forward&max_depth=8`, { token: adminToken });
    assert.equal(trace.status, 200);
    assert.ok(trace.body.nodes.some((node) => node.object_type === "operation"));

    const bop = await request(port, "GET", `/api/v1/requirement-manufacturing/bop/${bopRevision.id}/operations`, { token: adminToken });
    assert.equal(bop.status, 200);
    assert.ok(bop.body.items.some((item) => item.operation_object_id === String(operation.id)));

    const ebomMap = await request(port, "GET", `/api/v1/requirement-manufacturing/ebom/${ebomRevision.id}/mbom-mappings`, { token: adminToken });
    assert.equal(ebomMap.status, 200);
    assert.ok(ebomMap.body.summary.mappings >= 1);
  });
});
